import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const handleFetchIntegrationClick = async () => {
    return fetch('/api/integrations')
      .then(res => res.json())
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <p>Hello Next!</p>
        <button onClick={handleFetchIntegrationClick}>Fetch Integrations</button>
      </main>
    </>
  )
}
