name: Build and Deploy GH Pages

on:
  push:
    branches:
      - main
      - dev
    paths:
      - '.github/**'
      - 'playground/public-spa/**'

env:
  DEPLOY_REPO_BRANCH: gh-pages
  APP_BASE_PATH: '/keycloak-example-apps'
  SSO_REDIRECT_URI: 'https://bcgov.github.io/keycloak-example-apps'
  APP_ENV: 'prod'
  GITHUB_REGISTRY: ghcr.io
jobs:
  build-and-deploy:
    runs-on: ubuntu-24.04
    permissions: write-all
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Cache Docker layers for SSO Keycloak Example Apps
        uses: actions/cache@v5
        with:
          path: /tmp/.buildx-cache-sso-keycloak-example-apps
          key: ${{ runner.os }}-buildx-sso-keycloak-example-apps-${{ github.sha }}
          restore-keys: ${{ runner.os }}-buildx-sso-keycloak-example-apps-

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push SSO Keycloak Example Apps Docker image
        uses: docker/build-push-action@v7
        with:
          context: playground/public-spa
          file: playground/public-spa/Dockerfile
          push: true
          tags: ${{ env.GITHUB_REGISTRY }}/bcgov/sso-keycloak-example-apps:latest
          cache-from: type=local,src=/tmp/.buildx-cache-sso-keycloak-example-apps
          cache-to: type=local,dest=/tmp/.buildx-cache-sso-keycloak-example-apps-new,mode=max

        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: rm -rf /tmp/.buildx-cache-sso-keycloak-example-apps
          mv /tmp/.buildx-cache-sso-keycloak-example-apps-new /tmp/.buildx-cache-sso-keycloak-example-apps

      - name: Install and Build
        run: |
          yarn
          yarn build
          yarn export
          touch ./out/.nojekyll
        working-directory: ./playground/public-spa

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: ${{ env.DEPLOY_REPO_BRANCH }}
          folder: ./playground/public-spa/out

      - name: Create Release
        if: github.ref == 'refs/heads/main'
        id: release
        uses: rymndhng/release-on-push-action@v0.28.0
        with:
          bump_version_scheme: patch
          tag_prefix: v

      - name: Check Output Parameters
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Got tag name ${{ steps.release.outputs.tag_name }}"
          echo "Got release version ${{ steps.release.outputs.version }}"
          echo "Upload release artifacts to ${{ steps.release.outputs.upload_url }}"
