name: Build and Deploy GH Pages

on:
  push:
    branches:
      - main
      - dev
    paths:
      - '.github/**'
      - 'playground/public-spa/**'

env:
  DEPLOY_REPO_BRANCH: gh-pages
  APP_BASE_PATH: '/keycloak-example-apps'

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install and Build
        run: |
          yarn
          yarn build
          yarn export
          touch ./out/.nojekyll
        working-directory: ./playground/public-spa

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: ${{ env.DEPLOY_REPO_BRANCH }}
          folder: ./playground/public-spa/out

      - name: Create Release
        if: github.ref == 'refs/heads/main'
        id: release
        uses: rymndhng/release-on-push-action@v0.20.0
        with:
          bump_version_scheme: patch
          tag_prefix: v

      - name: Check Output Parameters
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Got tag name ${{ steps.release.outputs.tag_name }}"
          echo "Got release version ${{ steps.release.outputs.version }}"
          echo "Upload release artifacts to ${{ steps.release.outputs.upload_url }}"
