name: Build and Deploy GH Pages

on:
  push:
    branches:
      - main
      - dev
    paths:
      - '.github/**'
      - 'public-spa/**'

env:
  DEPLOY_REPO_BRANCH: gh-pages
  APP_BASE_PATH: '/keycloak-example-apps'

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install and Build
        run: |
          yarn
          yarn build
          yarn export
          touch ./out/.nojekyll
        working-directory: ./public-spa

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: ${{ env.DEPLOY_REPO_BRANCH }}
          folder: ./public-spa/out
