name: Build and Deploy GH Pages

on:
  push:
    branches:
      - main
      - dev
    paths:
      - '.github/**'
      - 'demo-spa-only/**'

env:
  SSO_CLIENT_ID: sso-requests
  DEPLOY_REPO_BRANCH: gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install and Build
        run: |
          yarn
          yarn build
          yarn export
          touch ./out/.nojekyll
        working-directory: ./demo-spa-only

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: ./demo-spa-only/out
